# Site settings
title: Fab B.
email: contact@fab-b.fr
permalink: /:categories/:title.html
description: > # this means to ignore newlines until "baseurl:"
  Les vidéos que vous trouverez ici sont faites dans le but de vous montrer que beaucoup de choses sont accessible à tous à condition d'oser se "salir" les mains. En suivant mes vidéos vous apprendrez des bases en mécanique ce qui vous permettra de faire des économies sur l'entretien de vos véhicules.

insta: https://www.instagram.com/fab_b_youtube/
youtube: https://www.youtube.com/channel/UCkqQ7ktU06DL8xqiqHdI2rw

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://romsys.ovh" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Gems et extensions
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
exclude:
- Dockerfile

collections_dir: collections

collections:
  articles:
    output: true
    permalink: /articles/:title
  comparatifs:
    output: true
    permalink: /comparatifs/:title
  videos:
  
sass:
  sass_dir: css
  style: compressed